/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGithubRouteImport } from './routes/_app/github'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplicationsIndexRouteImport } from './routes/_app/applications/index'
import { Route as ApiPdfIdRouteImport } from './routes/api/pdf/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppApplicationsNewRouteImport } from './routes/_app/applications/new'
import { Route as AppApplicationsIdRouteImport } from './routes/_app/applications/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGithubRoute = AppGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPdfIdRoute = ApiPdfIdRouteImport.update({
  id: '/api/pdf/$id',
  path: '/api/pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsNewRoute = AppApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/github': typeof AppGithubRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/applications/new': typeof AppApplicationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$id': typeof ApiPdfIdRoute
  '/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/github': typeof AppGithubRoute
  '/applications/$id': typeof AppApplicationsIdRoute
  '/applications/new': typeof AppApplicationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$id': typeof ApiPdfIdRoute
  '/applications': typeof AppApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/github': typeof AppGithubRoute
  '/_app/applications/$id': typeof AppApplicationsIdRoute
  '/_app/applications/new': typeof AppApplicationsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$id': typeof ApiPdfIdRoute
  '/_app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/github'
    | '/applications/$id'
    | '/applications/new'
    | '/api/auth/$'
    | '/api/pdf/$id'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/github'
    | '/applications/$id'
    | '/applications/new'
    | '/api/auth/$'
    | '/api/pdf/$id'
    | '/applications'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/github'
    | '/_app/applications/$id'
    | '/_app/applications/new'
    | '/api/auth/$'
    | '/api/pdf/$id'
    | '/_app/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPdfIdRoute: typeof ApiPdfIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/github': {
      id: '/_app/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof AppGithubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/': {
      id: '/_app/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/pdf/$id': {
      id: '/api/pdf/$id'
      path: '/api/pdf/$id'
      fullPath: '/api/pdf/$id'
      preLoaderRoute: typeof ApiPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/applications/new': {
      id: '/_app/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AppApplicationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$id': {
      id: '/_app/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGithubRoute: typeof AppGithubRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
  AppApplicationsNewRoute: typeof AppApplicationsNewRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGithubRoute: AppGithubRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
  AppApplicationsNewRoute: AppApplicationsNewRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPdfIdRoute: ApiPdfIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
